import = [ "~/.config/alacritty/local.toml" ]
live_config_reload = true

[window]
padding = { x = 5, y = 3 }
dynamic_title = true
opacity = 0.75
blur = true
startup_mode = "Maximized"

[scrolling]
history = 100000

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "V", mods = "Control|Shift", action = "ToggleViMode" },
    { key = "M", mods = "Control|Shift", action = "ToggleMaximized" }
]
